name: Caller Workflow Demo
run-name: ${{ github.actor }} is testing out Github Actions

on:
  workflow_dispatch:
#   pull_request:
#     types: [opened, closed]
#   push:
#     branches:
#       - main

jobs:
  calling-reuse-workflow-style:
    uses: ./.github/workflows/resuse-workflow-style.yml
    with:
      caller-name: Raisul Islam Shehab
      src-directory: src
      dependency-file: requirements.txt

  calling-reuse-workflow-test:
    if: github.event_name == 'pull_request' && github.event.pull_request.state == 'open'
    uses: ./.github/workflows/reuse-workflow-test.yml
    with:
      caller-name: Raisul Islam Shehab
      dependency-file: requirements.txt
      src-directory: src
      src-script: src/my_script.py
      src-test: src/test_script.py
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  calling-reuse-workflow-runAll:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    uses: ./.github/workflows/reuse-workflow-runAll.yml
    with:
      caller-name: Raisul Islam Shehab
      src-directory: src
      dependency-file: requirements.txt
      src-script: src/my_script.py
      src-test: src/test_script.py
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}