name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  my_first_job:
    name: My job
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}"

      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5.2.0
        with:
            python-version: '3.10'
            cache: 'pip'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: ensure code style consistency using 'flake8'
        run: flake8 src
        
      - name: Run the script
        env: 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python src/my-script.py

      - name: Test the script
        run: pytest --cov=src src/test_script.py
